apiVersion: v2
name: kyverno-playground
type: application
version: 0.3.5
appVersion: v0.3.5
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kyverno Playground Web Application
keywords:
  - kubernetes
  - nirmata
  - policy agent
  - validating webhook
  - admissions controller
sources:
  - https://github.com/kyverno/playground
maintainers:
  - name: Nirmata
    url: https://kyverno.io/
kubeVersion: ">=1.16.0-0"
